### ISSUE TITLE
Hiding NSS icon for users that are not logged in

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#100]
@Peijman Do we still want this functionality?

**Comment by Peijman** [comment]
I don't remember wanting this. As far as the NSS icon, I just want it to not show on the homepage unless the user or empathizer is logged in. It doesn't really matter if the empathizer sees it.

**Comment by SunyataZero** [comment]
Ok, what i worry about from a performance perspective is that there will be
many empathizers having the front page loaded and therefore we get an AJAX
call (for updating the skype status) every 5 seconds. Maybe not an issue
right now though, perhaps in the future

On Thu, Feb 26, 2015 at 5:12 PM, Peijman <notifications@github.com> wrote:

> I don't remember wanting this. As far as the NSS icon, I just want it to
> not show on the homepage unless the user or empathizer is logged in. It
> doesn't really matter if the empathizer sees it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/100#issuecomment-76206355>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
@Peijman I have changed the name of this issue so it is about what you are after instead. I've tried to implement this but it doesn't seem to work since nss already uses a shortcode itself and if we want to place our icon with a shortcode ourselves there seems to be a problem. Is it possible to move the nss icon to another page? We could then restrict access to the whole page instead, this i have already done for another page and can do again

**Comment by Peijman** [comment]
That's not a bad idea. An easy fix at least for now.

Peijman Kouretchian, CEO

Mica Stumpf COO

Empathy App

510.943.8310

http://www.empathyapp.org
empathyapp@gmail.com

**Comment by SunyataZero** [comment]
Ok, just need to know the exact design, then i'll get on it
Kind Regards,
Tord

On Thu, Feb 26, 2015 at 10:36 PM, Peijman <notifications@github.com> wrote:

> That's not a bad idea. An easy fix at least for now.
>
> Peijman Kouretchian, CEO
>
> Mica Stumpf COO
>
> Empathy App
>
> 510.943.8310
>
> http://www.empathyapp.org
> empathyapp@gmail.com
>
> On Thu, Feb 26, 2015 at 10:47 AM, Tord <notifications@github.com> wrote:
>
> > @Peijman <https://github.com/Peijman> I have changed the name of this
> > issue so it is about what you are after instead. I've tried to implement
> > this but it doesn't seem to work since nss already uses a shortcode
> itself
> > and if we want to place our icon with a shortcode ourselves there seems
> to
> > be a problem. Is it possible to move the nss icon to another page? We
> could
> > then restrict access to the whole page instead, this i have already done
> > for another page and can do again
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EmpathyApp/EmpathyApp/issues/100#issuecomment-76241220>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/100#issuecomment-76279252>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
* everyone who is logged in has access to the new skype page
* but only callers are redirected to that page when logging in
