### ISSUE TITLE
Nav bar not shown for Android browsers

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#118]
* Browsers: Chrome for Android, UC browser, Android browser
* OS: Android 4.0.3
* Browser: UC browser 10
* Frequency: 4/4

**Comment by SunyataZero** [comment]
Support request filed on the elegantthemes forum

**Comment by SunyataZero** [comment]
@Peijman Assigning this to you if you want to try to fix this by using the primary menu (please see previous email i sent) Kind Regards, Tord

**Comment by SunyataZero** [comment]
The elegantthemes support did not help much.. i think we need to try another menu

**Comment by Peijman** [comment]
Yeah, I don't see it on my iphone either.

**Comment by SunyataZero** [comment]
Fixed by adding this to the custom css in divi's ePanel. From elegantthemes support:

> Hi, Please add the following code to the Custom CSS box in the ePanel options:
```
.et_secondary_nav_only_menu #top-header, ul#et-secondary-nav {
display: block !important;
}
```
