### ISSUE TITLE
[ext dep] Default Skype signup does not work on FF (Linux), Safari (MacOS), Chrome (MacOS)

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#120]
Link given from the Wordpress Empathy App registration page: https://login.skype.com/account/signup-form

Should we change this to something else? MS account?

It works on iOS Safari and probably on IE as well

**Comment by SunyataZero** [comment]
I have talked with the skype support and they say that we can schedule a remote session with them if we have a MacOS computer by contacting them here:
https://support.skype.com/support_selection

**Comment by SunyataZero** [comment]
Possible ways to solve this issue:
* [ ] Let users sign up with an ms account as an alternative
* [ ] Clearing the cache (and asking users to do the same)

**Comment by SunyataZero** [comment]
@Peijman I managed to get it working this time on FF+Lubuntu, it's possible that we both made some mistake and that this was not reported (like for example including non-alphanumeric characters in the password which is standard but not allowed here)

**Comment by Peijman** [comment]
Also, it seems that only one empathizer had a problem signing up their
skype account (she was the least "tech" person). So I'm not worried about
it.

Peijman Kouretchian, CEO

Mica Stumpf COO

Empathy App

510.943.8310

http://www.empathyapp.org
empathyapp@gmail.com

**Comment by SunyataZero** [comment]
Ok, for the callers i think that the best thing may be to not give the link
to the online signup but instead direct the user to download skype instead.
This will probably solve this problem and make it easier for inexperienced
computer users. What do you think?

On Mon, Mar 9, 2015 at 10:44 PM, Peijman <notifications@github.com> wrote:

> Also, it seems that only one empathizer had a problem signing up their
> skype account (she was the least "tech" person). So I'm not worried about
> it.
>
> Peijman Kouretchian, CEO
>
> Mica Stumpf COO
>
> Empathy App
>
> 510.943.8310
>
> http://www.empathyapp.org
> empathyapp@gmail.com
>
> On Mon, Mar 9, 2015 at 12:04 PM, Tord <notifications@github.com> wrote:
>
> > @Peijman <https://github.com/Peijman> I managed to get it working this
> > time on FF+Lubuntu, it's possible that we both made some mistake and that
> > this was not reported (like for example including non-alphanumeric
> > characters in the password which is standard but not allowed here)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EmpathyApp/EmpathyApp/issues/120#issuecomment-77920155>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/120#issuecomment-77949899>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
@Peijman I've talked with the skype support and probably the best is to give the users the download link and ask them not to select facebook or microsoft accounts, can we go with this, all things considered?

**Comment by SunyataZero** [comment]
If we only want to show the message on the registration screen (and not on the login screen):
* Alt1: http://illuminatikarate.com/blog/change-wordpress-default-register-message/
* Possible alt 2: http://codex.wordpress.org/Class_Reference/WP_Screen

**Comment by SunyataZero** [comment]
@Peijman This is what it looks like now for both login and registration, is this ok with you?

![selection_051](https://cloud.githubusercontent.com/assets/10245688/6575200/cc7fde50-c72c-11e4-9895-95eac24f8764.png)

**Comment by Peijman** [comment]
Can you make the background of this page totally white color? Also above
the skype text please put:
in bigger letters and centered:

Registration:
Complete this 1 minute process to connect to an empathizer
(then add one line space here before the rest of the text)

Also make the first line you have (Your username is your valid skype name)
BOLD.

Thanks Tord!


Peijman Kouretchian, CEO

Mica Stumpf COO

Empathy App

510.943.8310

http://www.empathyapp.org
empathyapp@gmail.com

**Comment by SunyataZero** [comment]
I'll see if i can find time to do this
Kind Regards,
Tord

On Tue, Mar 10, 2015 at 5:32 PM, Peijman <notifications@github.com> wrote:

> Can you make the background of this page totally white color? Also above
> the skype text please put:
> in bigger letters and centered:
>
> Registration:
> Complete this 1 minute process to connect to an empathizer
> (then add one line space here before the rest of the text)
>
> Also make the first line you have (Your username is your valid skype name)
> BOLD.
>
> Thanks Tord!
>
>
> Peijman Kouretchian, CEO
>
> Mica Stumpf COO
>
> Empathy App
>
> 510.943.8310
>
> http://www.empathyapp.org
> empathyapp@gmail.com
>
> On Tue, Mar 10, 2015 at 5:53 AM, Tord <notifications@github.com> wrote:
>
> > @Peijman <https://github.com/Peijman> This is what it looks like now for
> > both login and registration, is this ok with you?
> >
> > [image: selection_051]
> > <
> https://cloud.githubusercontent.com/assets/10245688/6575200/cc7fde50-c72c-11e4-9895-95eac24f8764.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EmpathyApp/EmpathyApp/issues/120#issuecomment-78046926>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/120#issuecomment-78091724>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
Have now linked to downloading skype instead of just signing up (which was better in any case) so this issue is "obsolete"
