### ISSUE TITLE
AJAX calls will run all WP init functions

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#121]
So we get a call to (for example) the function that initiates the db. In total it will be a lot and could maybe slow down our system significantly

**Comment by SunyataZero** [comment]
@puneetkhanal Hi, do you know if this is expected behavior? Kind Regards, Tord

**Comment by SunyataZero** [comment]
Two possible causes that i can think of:
1. Neat Skype Status and AJAX?
2. WP heartbeat problem

**Comment by puneetkhanal** [comment]
Too many db connections are being created, is it the case?

**Comment by SunyataZero** [comment]
No but just in general the init code is entered all the time not matter
what the function is, possibly the same with other levels of wordpress
functions, worried that this will slow down our system. I didn't expect
this to happen... yes Wordpress will go through this list
http://codex.wordpress.org/Plugin_API/Action_Reference
but will it go through for even a single AJAX call? Seems strange to me
Kind Regards,
Tord

On Sun, Mar 8, 2015 at 10:51 PM, puneetkhanal <notifications@github.com>
wrote:

> Too many db connections are being created, is it the case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/121#issuecomment-77776697>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
@puneetkhanal Reference: http://codex.wordpress.org/Plugin_API/Action_Reference#Actions_Run_During_a_Typical_Request

**Comment by puneetkhanal** [comment]
Yes, init() is called for each request, so we should not create the resource or time consuming operations in init(). We should make sure that all the resource or time consuming is handled in sever side. Is there any special operations being done it init()? I haven't worked with wordpress but I am drawing this conclusion based on my experience with servlets and jsp.

**Comment by SunyataZero** [comment]
Right now only the db code is run there, i got this from the wordpress
documentation so not sure if i want to change it now. But it's very good to
know that we are not doing anything "wrong" at least, thank you for your
help!
Kind Regards,
Tord

On Sun, Mar 8, 2015 at 11:11 PM, puneetkhanal <notifications@github.com>
wrote:

> Yes, init() is called for each request, so we should not create the
> resource or time consuming operations in init(). We should make sure that
> all the resource or time consuming is handled in sever side. Is there any
> special operations being done it init()? I haven't worked with wordpress
> but I am drawing this conclusion based on my experience with servlets and
> jsp.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/121#issuecomment-77777802>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
This is expected behavior, closing this issue, thank you @puneetkhanal for your help
