### ISSUE TITLE
[ext dep] Showing on web is unavailable in Android

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#124]
Is this also a problem for other platforms like iPhone?

**Comment by SunyataZero** [comment]
@Peijman It's important that our empathizers are aware of this. I've written a comment with a suggested workaround in the empathizer tech guide:
https://docs.google.com/document/d/1pHQBjZv7ZGsPAAV-hl0Ii9Gh_rjrpX2W2P8b3bLi2ss/edit#

**Comment by Peijman** [comment]
Thanks!

Peijman Kouretchian, CEO

Mica Stumpf COO

Empathy App

510.943.8310

http://www.empathyapp.org
empathyapp@gmail.com

**Comment by SunyataZero** [comment]
Will you update the document with info? Also i'm not sure what happens on
iPhone so maybe checking this first and then updating?
Kind Regards, Tord

On Tue, Mar 10, 2015 at 5:43 PM, Peijman <notifications@github.com> wrote:

> Thanks!
>
> Peijman Kouretchian, CEO
>
> Mica Stumpf COO
>
> Empathy App
>
> 510.943.8310
>
> http://www.empathyapp.org
> empathyapp@gmail.com
>
> On Tue, Mar 10, 2015 at 6:29 AM, Tord <notifications@github.com> wrote:
>
> > @Peijman <https://github.com/Peijman> It's important that our
> empathizers
> > are aware of this. I've written a comment with a suggested workaround in
> > the empathizer tech guide:
> >
> >
> https://docs.google.com/document/d/1pHQBjZv7ZGsPAAV-hl0Ii9Gh_rjrpX2W2P8b3bLi2ss/edit#
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EmpathyApp/EmpathyApp/issues/124#issuecomment-78052317>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/124#issuecomment-78094591>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
Updated the empathizer tech document and added to the list of defects, so closing this issue now
