### ISSUE TITLE
Preliminary testing of skype and neat skype status

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#32]
Testing this out in more detail than previously since we rely on it so much

**Comment by SunyataZero** [comment]
@Peijman Hi, i'm going through the issue list right now, i'm wondering if it's ok that i assign this issue to you?

**Comment by SunyataZero** [comment]
Defects in NSS and Skype can be found in [this file](https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/dependencies/risks-and-defects.md)

**Comment by Peijman** [comment]
should we close this one as well since our tests were good?

**Comment by SunyataZero** [comment]
yes! closing it now, feels good to close so many issues
