### ISSUE TITLE
Creating a landing page

### ISSUE THREAD

**Issue by Peijman** [EmpathyApp/EmpathyApp#33]
Temporary landing page so we can transfer domain.

**Comment by SunyataZero** [comment]
Hi, just so there's no problem down the road: as i understand it the
transfer is normally done during the purchase/setup of the arvixe hosting
when we would normally choose a domain name (it's possible that this could
be done another way that i don't know about)

On Mon, Jan 5, 2015 at 10:03 PM, Peijman <notifications@github.com> wrote:

> Temporary landing page so we can transfer domain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/33>.
>



-- 
http://www.svenskafreds.se/fredskalender-for-goteborg
https://github.com/EmpathyApp/EmpathyApp/
http://ihavearrived.org/
