### ISSUE TITLE
Error handling and design for Stripe

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#40]
* [ ] extra important: error handling for stripe ([link](http://stackoverflow.com/questions/17750143/catching-stripe-errors-with-try-catch-php-method))
* etc

**Comment by prashanthr** [comment]
https://stripe.com/docs/api?lang=php

**Comment by SunyataZero** [comment]
@prashanthr Can we close this issue? I'm really happy with the error handling for stripe now

**Comment by prashanthr** [comment]
Unit Tests should be written later. Maybe another low priority issue for the first version but will be high priority for subsequent versions.

**Comment by SunyataZero** [comment]
Yes, i've been looking into unit testing and it's possible to use phpunit for our code (even though it's basically procedural), for more info please see issue #27. I agree that we wait with unit testing until later
