### ISSUE TITLE
Pre-populate stripe email field in with email from user profile

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#55]
Right now the user needs to enter her email in the stripe dialog even though she has already given an email address when registering on the website.

![selection_718](https://cloud.githubusercontent.com/assets/10245688/5862995/af6ac15c-a276-11e4-8db4-7ba247304ce6.png)

**Comment by sebaste** [comment]
Part of this solution from another Github project was used to solve this issue:
https://github.com/pderksen/WP-Stripe-Checkout/blob/master/stripe/includes/shortcodes.php

**Comment by SunyataZero** [comment]
Nice, i like this clean solution
Kind Regards,
Tord

On Wed, Jan 28, 2015 at 7:43 AM, sebaste <notifications@github.com> wrote:

> Part of this solution from another Github project was used to solve this
> issue:
>
> https://github.com/pderksen/WP-Stripe-Checkout/blob/master/stripe/includes/shortcodes.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/55#issuecomment-71788645>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/
