### ISSUE TITLE
Arvixe shared hosting cpu reaches max when 40 clients connect within 1 minute

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#57]
First testing with http://loader.io/ and firebug:
* 25 requests (mostly get) for a normal call
  * 5 minutes = 300 seconds
  * This gives us ~0.1 req/s
* Now we need to add the requests for skype status updates
  * One update every 5 seconds
  * gives us 0.2 req/s
* Total: 0.3 req/s

Then comparing to when we hit the cpu limit (using the left-hand side info in arvixe's cpanel):
* 1 req/second (already it has become slow by then, so maybe 0.5)
* Also note that we are having many subdomains running, and this may take up a lot as well
  * ***We may need to run these tests on the www.empathyapp.org domain***

Using this information we get:
* Conclusion: only 3 users can connect with these assumptions

*Suggested fix: Contacting arvixe and asking them to increase alloted cpu*

***How will the position of the server effect this test?***

Loader.io results:
 * [link](http://ldr.io/1wsA50B)

**Comment by SunyataZero** [comment]
Load test
Duration: 1 min

8351 ms average response time
40.0 % average error rate

Successful responses: 21

Received† 	169 KB
Sent 	5.81 KB
† "Received" refers to data received by the clients
Average response time across tests
(ms)

Errors
Timeouts 	14
Network 	0
400 	0
500 	0

**Comment by SunyataZero** [comment]
**Searching for arvixe:**
http://forum.arvixe.com/smf/general/high-cpu-usage/
http://forum.arvixe.com/smf/general/high-cpu-usage/5/?wap2

**Comment by SunyataZero** [comment]
Peijman wrote:
>I think we should be ready to have up to 5 empathizers online at the same time. Most often there will only be 1-3 online at the same time at the beginning. But if we are prepared to have up to 5 empathizers online then we should be prepared for the first couple of months at the very least.

**Comment by SunyataZero** [comment]
@Peijman Have you been able to test empathy app with several people at once? This would be the best, to actually be able to measure the load during the real conditions. Then we could also use the information we gained from this (assuming that i can run my tests during the same time period) to calcluate how to run the load tests in the future

**Comment by Peijman** [comment]
This is my next testing area.

**Comment by SunyataZero** [comment]
@Peijman Alright! I think this will help us alot, i'd be happy to help out with this testing and run some tools (now i'm thinking of loader.io) during a time period when you are testing

**Comment by SunyataZero** [comment]
Closing this issue after having run tests earlier today and also talked with the arvixe support which calmed my fears:
https://docs.google.com/document/d/1SUIQug-AoPBW_RB1_q6dMGVtcqXFMFPuhblg4XnlZ3Q/edit?usp=sharing
