### ISSUE TITLE
NetworkError: 404 Not Found for square-image.png in donation-form_sc.php

### ISSUE THREAD

**Issue by sebaste** [EmpathyApp/EmpathyApp#65]
I noticed this error in Firebug when starting the Stripe checkout dialogue:
"NetworkError: 404 Not Found - http://tolstoy.ihavearrived.org/square-image.png".

Either we need to include the square-image.png or we need to stop setting the 'image' variable in StripeCheckout.open().

**Comment by SunyataZero** [comment]
One of the problems is that access to image files (or any files) are non-standard in wp, please see this link for more info:
http://stackoverflow.com/questions/5221630/wordpress-path-url-in-js-script-file

**Comment by prashanthr** [comment]
Does a sort of URI navigation framework solve this problem? If we can create a class handler that always gives us the absolute path to an entity (For example: image folder root, Stripe library root etc), we can use that to solve this problem. Upload the files and give it a go.

**Comment by SunyataZero** [comment]
Hi, please use images/logo_256x256.png
Kind Regards, Tord

**Comment by prashanthr** [comment]
Updated use of logo

**Comment by SunyataZero** [comment]
Nice to see the icon in the stripe checkout!
Kind Regards, Tord

On Sun, Feb 1, 2015 at 7:27 PM, Prashanth Rajaram <notifications@github.com>
wrote:

> Closed #65 <https://github.com/EmpathyApp/EmpathyApp/issues/65>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/65#event-228172792>.
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/
