### ISSUE TITLE
Filtering form input

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#69]
One of the goals is to avoid sql injection attacks

**Comment by SunyataZero** [comment]
@Sunnygolden8 Hi, i'm assigning this issue to you since you're best on this area, hope this is ok, otherwise please tell me and i'll remove you. Also if you like me not to do this in the future feel free to tell me

**Comment by Sunnygolden8** [comment]
I'll see what I can do here.

**Comment by SunyataZero** [comment]
Thank you!

On Sun, Feb 1, 2015 at 11:21 PM, Christine Lam <notifications@github.com>
wrote:

> I'll see what I can do here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/69#issuecomment-72387885>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by SunyataZero** [comment]
@Sunnygolden8 Hi, are you making progress on this issue? Could really use your help since the BETA-release is coming up soon

**Comment by SunyataZero** [comment]
moving this issue to our security issue list
