### ISSUE TITLE
Donating without being logged in ( + New db design?)

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#74]
* [x] Create token
* [x] Use token in GET params

**Comment by SunyataZero** [comment]
@prashanthr Hi, i've started working on this issue, i'm thinking to myself "why not just give the username as a GET parameter?", yes someone could fake this, but why would they want to? (since the only thing that would happen is that the person faking it would be paying for it seeming that another user is contributing more money than they actually are. Maybe i'm missing something not sure, because when we talked your token idea seemed better, i guess i'm a bit confused

**Comment by SunyataZero** [comment]
Changed to high-prio because i will fix some other important things at the same time

**Comment by SunyataZero** [comment]
Generating a token:
http://php.net/manual/en/function.uniqid.php

**Comment by prashanthr** [comment]
@SunyataZero Using the username would definitely be a simpler implementation and the problem may be partially resolved by using this approach. 

There are many useful use cases for using a token or special identifier for a transaction/data row in a database. 
Let's assume 2 transactions
1) User1 calls Empathizer1 today - Transaction 1
2) User1 calls Empathizer1 tomorrow - Transaction 2

Using "User1" and "Empathizer1", we can create a transaction for today with all the required information. What will happen for tomorrow's transaction? Will the code update the same transaction in the database? Maybe we could time stamp it as well which would mean at least 3 GET parameters including but not limited to username, recommended amount, timestamp etc. This may just continue to increase in complexity. 

Assuming we create a transaction at the very first step - the user1 and empathizer1 are connected. We can generate a unique id/token for that transaction and use that for any following actions (sending donation e-mails/clicking links/recording payment or transaction data etc.) as that unique token/id will identify that transaction throughout it's lifetime and we will not run into any issues. Tokens/unique Ids can't be easily faked either. 

This is my way of thinking of this problem. The advantages include an entire tracking of various actions linked to one transaction in the database. We could of course extend the database structure to record various things related to the same transaction. (1 table for donation amounts, 1 table for user/empathizer info etc. - all relating to same transaction identifier. This will be useful when our database grows - users, transactions etc.)

**Comment by SunyataZero** [comment]
@prashanthr Thank you so much for the input and analysis, i agree that this will be a better solution and i'll probably use the "uniqid" php function for generating the token

**Comment by SunyataZero** [comment]
md5 seems much better from a security perspecive so i'll use this instead

**Comment by SunyataZero** [comment]
Still to do: Finding a way to generate a *unique* token
https://www.google.se/search?client=ubuntu&channel=fs&q=php+unique+secure+token&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=jJvkVOCUJIKe-wbFiICIDg

**Comment by SunyataZero** [comment]
quality review needed, but closing for now
