### ISSUE TITLE
neat skype status error message

### ISSUE THREAD

**Issue by Peijman** [EmpathyApp/EmpathyApp#78]
This error message shows up at the top of the page: even though it looks like it is working. 
neat skype status error thing: undefined variable return_value on line 406

**Comment by SunyataZero** [comment]
Yes, this is a known minor bug in neat skype status, i'll add it to our
file [risks and defects](
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/dependencies/risks-and-defects.md
)

On Thu, Feb 12, 2015 at 10:18 PM, Peijman <notifications@github.com> wrote:

> This error message shows up at the top of the page: even though it looks
> like it is working.
> neat skype status error thing: undefined variable return_value on line 406
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/78>.
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by Peijman** [comment]
but how do we get rid of it? Is there a way? It wasn't showing up before.....

**Comment by SunyataZero** [comment]
Yes, it's because we are printing many much debug/warning messages as possible, i have created this issue #72 for dealing with this. Will still keep this issue open until the other one is fixed

**Comment by SunyataZero** [comment]
Have now updated this file
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/dependencies/risks-and-defects.md
with the neat skype status warning/notice

**Comment by Peijman** [comment]
ok so when we go live, we can fix this easily by printing less messages?

**Comment by SunyataZero** [comment]
yes, but it would be nice to automate this process, so i'm keeping this
issue open for now if that's ok



On Thu, Feb 12, 2015 at 10:31 PM, Peijman <notifications@github.com> wrote:

> ok so when we go live, we can fix this easily by printing less messages?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EmpathyApp/EmpathyApp/issues/78#issuecomment-74157111>
> .
>



-- 
https://github.com/EmpathyApp/EmpathyApp/
<http://www.svenskafreds.se/fredskalender-for-goteborg>
http://ihavearrived.org/

**Comment by Peijman** [comment]
great, I am taking priority off then.

**Comment by SunyataZero** [comment]
@sebaste Assigning this to you since it's connected with another issue you have, hope this is ok?

**Comment by SunyataZero** [comment]
Closing this issue since we have a tempoaray fix in place now and the long-term solution will be to create a separate build for the release
