### ISSUE TITLE
wordpress: how to have a different navigation bar for empathizers, and a different one for users

### ISSUE THREAD

**Issue by Peijman** [EmpathyApp/EmpathyApp#80]
?

**Comment by SunyataZero** [comment]
@Peijman a bit confused: do you mean that access should be restricted to certain pages and that each role sees only links to the pages available for her role? or are you thinking of the top nav bar (that we see in the admin interface)?

**Comment by Peijman** [comment]
I fixed this so Im closing this issue. I have given different access to the empathizers and users. Now for example the email form only appears on the navigation bar if you are an empathizer. Users dont even see it, and just in case its a smart hacker and they know the url, they will still be redirected to login.
