### ISSUE TITLE
skype redirects incoming calls to phone

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#82]
Peijman: Also when using skype on my phone, if i don't answer with skype, skype calls my phone. How to disable this? Also this should be documented so empathizers will know how to deal with it.

Peijman: It even calls me if I am signed out of skype! Oh my god. Attack of the empathy users! :)

**Comment by SunyataZero** [comment]
@Peijman: don't think there's a way around this other than simply removing the phone number from the empathizer accounts. Maybe this is ok since we are advicing empathizers to use a separate account for empathy app calls?
https://github.com/EmpathyApp/EmpathyApp/blob/master/docs/misc/empathizer-user-guide.md

Closing this issue (but leaving #81 open) if that is ok?

**Comment by Peijman** [comment]
This is resolved, and now updated in the empathizer user-guide, so closing this issue.
