### ISSUE TITLE
Fixing Email form page look

### ISSUE THREAD

**Issue by Peijman** [EmpathyApp/EmpathyApp#84]
The email form looks a bit strange the text doesnt match with the box to enter the data

https://www.empathyapp.org/email-form/

**Comment by SunyataZero** [comment]
@Peijman i don't understand, can you include a screenshot in this issue?

**Comment by Peijman** [comment]
![screen shot 2015-02-13 at 8 47 55 am](https://cloud.githubusercontent.com/assets/10391959/6191284/0f65f8be-b35d-11e4-840e-ef2490c3d2aa.png)
Seems like it needs to be on another line, and also if you add an empty line after the call duration box so its not too close to the submit button would be great

**Comment by SunyataZero** [comment]
oh, sorry, i got to the login page and therefore thought it was the login (which looks good to me), i'll check this out

**Comment by SunyataZero** [comment]
This is what i see on http://coetzee.ihavearrived.org/email-form/
![selection_733](https://cloud.githubusercontent.com/assets/10245688/6192725/463db978-b3b5-11e4-8da6-420dd4987880.png)

I think it depends on the theme and on css (css is a way to "style" html)

**Comment by SunyataZero** [comment]
CSS tutorial: http://www.w3schools.com/css/
