### ISSUE TITLE
NSS queue system does not seem to work sometimes

### ISSUE THREAD

**Issue by SunyataZero** [EmpathyApp/EmpathyApp#86]
```[skype skypenames="echo123, tord_dellsen, infinitytaal"]```

For example shows "echo123" even though tord_dellsen is online. Have tried reloading but no luck, it seems that this problem is active under some time periods. Frequency: approx. 3/20

**Comment by Peijman** [comment]
queue system worked fine today. So I think we should close this.

**Comment by SunyataZero** [comment]
Alright, closing this as well

**Comment by SunyataZero** [comment]
@Peijman: Reopening this issue since i've seen it again
Maybe has something to do with my gnu/linux skype client

**Comment by SunyataZero** [comment]
Update: More evidence that it may be the Linux client: I've had problems with the skype status not updating when i start using the computer, therefore i'm closing this issue for now

**Comment by SunyataZero** [comment]
If i manually change status it will be updated in nss. Maybe the signal has not been sent to the skype servers?
